'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Schussberechnung.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Only numbers are allowed! ähnelt.
        '''</summary>
        Friend ReadOnly Property NumericInputOnly() As String
            Get
                Return ResourceManager.GetString("NumericInputOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Numbers Only! ähnelt.
        '''</summary>
        Friend ReadOnly Property NumericInputOnlyTitle() As String
            Get
                Return ResourceManager.GetString("NumericInputOnlyTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die A website will be loaded where you can report the bugs you have found. If you do not have an account yet, you can create one by clicking &apos;Signup for a new account&apos;, otherwise please click on &apos;Login&apos;. ähnelt.
        '''</summary>
        Friend ReadOnly Property strBugReport() As String
            Get
                Return ResourceManager.GetString("strBugReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die A website will be loaded showing the latest changes made to this program. ähnelt.
        '''</summary>
        Friend ReadOnly Property strChangelog() As String
            Get
                Return ResourceManager.GetString("strChangelog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please choose the Path for the file. ähnelt.
        '''</summary>
        Friend ReadOnly Property strChosePath() As String
            Get
                Return ResourceManager.GetString("strChosePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        '''</summary>
        Friend ReadOnly Property strDeleteTitle() As String
            Get
                Return ResourceManager.GetString("strDeleteTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please enter the number of shots ähnelt.
        '''</summary>
        Friend ReadOnly Property strEnterShots() As String
            Get
                Return ResourceManager.GetString("strEnterShots", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please enter the x ähnelt.
        '''</summary>
        Friend ReadOnly Property strEnterXPart1() As String
            Get
                Return ResourceManager.GetString("strEnterXPart1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die -coordinates. ähnelt.
        '''</summary>
        Friend ReadOnly Property strEnterXPart2() As String
            Get
                Return ResourceManager.GetString("strEnterXPart2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please enter the y ähnelt.
        '''</summary>
        Friend ReadOnly Property strEnterYPart1() As String
            Get
                Return ResourceManager.GetString("strEnterYPart1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die -coordinates. ähnelt.
        '''</summary>
        Friend ReadOnly Property strEnterYPart2() As String
            Get
                Return ResourceManager.GetString("strEnterYPart2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die A website will be loaded showing a help-article about this software. Unfortunately, it is available in German only at the moment. ähnelt.
        '''</summary>
        Friend ReadOnly Property strHelp() As String
            Get
                Return ResourceManager.GetString("strHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You have not entered a valid number. Would you like to quit the program? ähnelt.
        '''</summary>
        Friend ReadOnly Property strNotValid() As String
            Get
                Return ResourceManager.GetString("strNotValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete this file? ähnelt.
        '''</summary>
        Friend ReadOnly Property strSure() As String
            Get
                Return ResourceManager.GetString("strSure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Quit? ähnelt.
        '''</summary>
        Friend ReadOnly Property strTitleNotValid() As String
            Get
                Return ResourceManager.GetString("strTitleNotValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die number of shots ähnelt.
        '''</summary>
        Friend ReadOnly Property strTitleShots() As String
            Get
                Return ResourceManager.GetString("strTitleShots", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die get_x ähnelt.
        '''</summary>
        Friend ReadOnly Property strTitleX() As String
            Get
                Return ResourceManager.GetString("strTitleX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die get_y ähnelt.
        '''</summary>
        Friend ReadOnly Property strTitleY() As String
            Get
                Return ResourceManager.GetString("strTitleY", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
